最常用的算法是反向传播算法。在该算法中，根据损失函数相对于给定参数的梯度来调整参数

In [3]:
import torch 
from torch import nn as nn
from torch.nn import functional as F 

In [17]:
x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5,3,requires_grad=True)
b = torch.randn(3, requires_grad=True) # 通过初始化的设置让tensor自动计算梯度
z = torch.matmul(x,w)+b
loss = F.binary_cross_entropy_with_logits(z, y)
print(loss)

tensor(0.9461, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [9]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x127a55460>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x127a555b0>


## 计算梯度

In [18]:
loss.backward() # 计算反向传播的梯度
print(w.grad)
print(b.grad)

tensor([[0.0157, 0.2168, 0.2748],
        [0.0157, 0.2168, 0.2748],
        [0.0157, 0.2168, 0.2748],
        [0.0157, 0.2168, 0.2748],
        [0.0157, 0.2168, 0.2748]])
tensor([0.0157, 0.2168, 0.2748])


## 梯度跟踪设置

In [19]:
z = torch.matmul(x,w)+b
print(z.requires_grad) # 说明此时z是会被跟踪梯度的

True


In [20]:
with torch.no_grad():
    z_no = torch.matmul(x, w)+b # 通过加上设置能让原来的tensor不再被跟踪
print(z_no.requires_grad)

False


In [22]:
z = torch.matmul(x, w)+b
print(z.requires_grad)
z_det = z.detach() #通过detach()一键让原来的tensor不再跟踪
print(z_det.requires_grad)

True
False


## 线性回归

In [1]:
def f(x):
    '''计算y'''
    y = x**2 * torch.exp(x)
    return y

def gradf(x):
    '''手动求导函数'''
    dx = 2*x*torch.exp(x) + x**2*torch.exp(x)
    return dx

In [ ]:
# 计算函数的值并初始化参数的包含梯度的tensor
x = torch.randn(3,4, requires_grad = True)
y = f(x)
y

tensor([[12.0580,  0.0829,  0.5223,  0.0126],
        [ 0.3488,  1.4332,  0.2336,  0.5336],
        [ 0.1433,  0.2118,  6.2621,  1.6403]], grad_fn=<MulBackward0>)

In [6]:
y.backward(torch.ones(y.size())) # gradient形状与y一致
x.grad

tensor([[27.3431, -0.4025, -0.1128,  0.2492],
        [-0.3860,  5.0083,  1.4121,  0.0592],
        [-0.4518, -0.4596, 15.8676,  5.5408]])

In [5]:
# autograd的计算结果与利用公式手动计算的结果一致
gradf(x)

tensor([[27.3431, -0.4025, -0.1128,  0.2492],
        [-0.3860,  5.0083,  1.4121,  0.0592],
        [-0.4518, -0.4596, 15.8676,  5.5408]], grad_fn=<AddBackward0>)